# Res152

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [2]:
sess = tf.InteractiveSession()

In [3]:
newsaver=tf.train.import_meta_graph('/home/stream/whimh2.0/Bibi/trained_model/resnet152.ckpt.meta')
newsaver.restore(sess,'/home/stream/whimh2.0/Bibi/trained_model/resnet152.ckpt')

In [4]:
feature_x=np.load("/home/stream/whimh2.0/Bibi/test_res_152_scale5.npy")

In [5]:
y_ID=np.load("/home/stream/whimh2.0/Bibi/test_ID.npy")

In [6]:
#[i.name for i in graph.get_operations()]
#operation_name=[i.name for i in graph.get_operations()]
#[i for i in operation_name if 'predictions_softmax' in i]
graph = tf.get_default_graph()
predctions=graph.get_tensor_by_name("fintune_whimh/measure/predict/predictions_:0")
soft_predctions=graph.get_tensor_by_name("fintune_whimh/Fc2/predictions_softmax:0")

x_tfed=graph.get_tensor_by_name("feature_x:0")
keep_prob=graph.get_tensor_by_name("fintune_whimh/Placeholder:0")

In [7]:
print keep_prob
print x_tfed
print predctions

Tensor("fintune_whimh/Placeholder:0", dtype=float32)
Tensor("feature_x:0", shape=(?, 7, 7, 2048), dtype=float32)
Tensor("fintune_whimh/measure/predict/predictions_:0", shape=(?,), dtype=int64)


In [8]:
w=sess.run(soft_predctions, feed_dict={x_tfed:feature_x[:5],keep_prob:1.0})

In [9]:
print [max(i) for i in w]
print y_ID[:5]

[0.99996793, 0.99891484, 0.99866033, 0.99912721, 0.9997825]
[    1    10   100  1000 10000]


In [10]:
train_writer = tf.train.SummaryWriter('/tmp/loser1/train',sess.graph)

In [11]:
testing_prob=sess.run(soft_predctions, feed_dict={x_tfed:feature_x,keep_prob:1.0})

In [12]:
print [i[1] for i in w]
print y_ID[:5]

[0.99996793, 0.0010852262, 0.0013396894, 0.99912721, 0.9997825]
[    1    10   100  1000 10000]


In [13]:
testing_prob= [i[1]  for i in testing_prob]

In [14]:
data=zip(testing_prob,y_ID)

In [15]:
import csv
f = open("/home/stream/whimh2.0/Bibi/res152_test.csv","w")
w = csv.writer(f)
w.writerows(data)
f.close()

In [16]:
tf.reset_default_graph()
sess.close()

# Res101

In [17]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [18]:
sess = tf.InteractiveSession()

In [19]:
newsaver=tf.train.import_meta_graph('/home/stream/whimh2.0/Bibi/trained_model/resnet101.ckpt.meta')
newsaver.restore(sess,'/home/stream/whimh2.0/Bibi/trained_model/resnet101.ckpt')

In [20]:
feature_x=np.load("/home/stream/whimh2.0/Bibi/test_res_101_scale5.npy")

In [21]:
y_ID=np.load("/home/stream/whimh2.0/Bibi/test_ID.npy")

In [22]:
#[i.name for i in graph.get_operations()]
#operation_name=[i.name for i in graph.get_operations()]
#[i for i in operation_name if 'predictions_softmax' in i]
graph = tf.get_default_graph()
predctions=graph.get_tensor_by_name("fintune_whimh/measure/predict/predictions_:0")
soft_predctions=graph.get_tensor_by_name("fintune_whimh/Fc2/predictions_softmax:0")

x_tfed=graph.get_tensor_by_name("feature_x:0")
keep_prob=graph.get_tensor_by_name("fintune_whimh/Placeholder:0")

In [23]:
print keep_prob
print x_tfed
print predctions

Tensor("fintune_whimh/Placeholder:0", dtype=float32)
Tensor("feature_x:0", shape=(?, 7, 7, 2048), dtype=float32)
Tensor("fintune_whimh/measure/predict/predictions_:0", shape=(?,), dtype=int64)


In [24]:
w=sess.run(soft_predctions, feed_dict={x_tfed:feature_x[:5],keep_prob:1.0})

In [25]:
print [i[1] for i in w]
print y_ID[:5]
#1 0 0 1 1

[0.99995697, 0.00010391106, 0.00058329792, 0.99982625, 0.99973255]
[    1    10   100  1000 10000]


In [26]:
#train_writer = tf.train.SummaryWriter('/tmp/loser1/train',sess.graph)

In [27]:
testing_prob=sess.run(soft_predctions, feed_dict={x_tfed:feature_x,keep_prob:1.0})

In [28]:
testing_prob= [i[1]  for i in testing_prob]

In [29]:
data=zip(testing_prob,y_ID)

In [30]:
import csv
f = open("/home/stream/whimh2.0/Bibi/res101_test.csv","w")
w = csv.writer(f)
w.writerows(data)
f.close()

In [31]:
tf.reset_default_graph()
sess.close()

# res 50

In [32]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [33]:
sess = tf.InteractiveSession()

In [34]:
newsaver=tf.train.import_meta_graph('/home/stream/whimh2.0/Bibi/trained_model/resnet50.ckpt.meta')
newsaver.restore(sess,'/home/stream/whimh2.0/Bibi/trained_model/resnet50.ckpt')

In [35]:
feature_x=np.load("/home/stream/whimh2.0/Bibi/test_res_50_scale5.npy")

In [36]:
y_ID=np.load("/home/stream/whimh2.0/Bibi/test_ID.npy")

In [37]:
#[i.name for i in graph.get_operations()]
#operation_name=[i.name for i in graph.get_operations()]
#[i for i in operation_name if 'predictions_softmax' in i]
graph = tf.get_default_graph()
predctions=graph.get_tensor_by_name("fintune_whimh/measure/predict/predictions_:0")
soft_predctions=graph.get_tensor_by_name("fintune_whimh/Fc2/predictions_softmax:0")

x_tfed=graph.get_tensor_by_name("feature_x:0")
keep_prob=graph.get_tensor_by_name("fintune_whimh/Placeholder:0")

In [38]:
print keep_prob
print x_tfed
print predctions

Tensor("fintune_whimh/Placeholder:0", dtype=float32)
Tensor("feature_x:0", shape=(?, 7, 7, 2048), dtype=float32)
Tensor("fintune_whimh/measure/predict/predictions_:0", shape=(?,), dtype=int64)


In [39]:
w=sess.run(soft_predctions, feed_dict={x_tfed:feature_x[:5],keep_prob:1.0})

In [40]:
print [i[1] for i in w]
print y_ID[:5]
#1 0 0 1 1

[0.99766529, 0.00015542915, 0.0028952826, 0.9993242, 0.99872178]
[    1    10   100  1000 10000]


In [41]:
#train_writer = tf.train.SummaryWriter('/tmp/loser1/train',sess.graph)

In [42]:
testing_prob=sess.run(soft_predctions, feed_dict={x_tfed:feature_x,keep_prob:1.0})

In [43]:
testing_prob= [i[1]  for i in testing_prob]

In [44]:
data=zip(testing_prob,y_ID)

In [45]:
import csv
f = open("/home/stream/whimh2.0/Bibi/res50_test.csv","w")
w = csv.writer(f)
w.writerows(data)
f.close()

In [46]:
tf.reset_default_graph()
sess.close()

# vgg16 pool5

In [47]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [48]:
sess = tf.InteractiveSession()

In [49]:
newsaver=tf.train.import_meta_graph('/home/stream/whimh2.0/Bibi/trained_model/vgg_pool5.ckpt.meta')
newsaver.restore(sess,'/home/stream/whimh2.0/Bibi/trained_model/vgg_pool5.ckpt')

In [50]:
feature_x=np.load("/home/stream/whimh2.0/Bibi/test_vgg_pool5.npy")

In [51]:
y_ID=np.load("/home/stream/whimh2.0/Bibi/test_ID.npy")

In [52]:
#[i.name for i in graph.get_operations()]
#operation_name=[i.name for i in graph.get_operations()]
#[i for i in operation_name if 'predictions_softmax' in i]
graph = tf.get_default_graph()
predctions=graph.get_tensor_by_name("fintune_whimh/measure/predict/predictions_:0")
soft_predctions=graph.get_tensor_by_name("fintune_whimh/Fc2/predictions_softmax:0")

x_tfed=graph.get_tensor_by_name("feature_x:0")
keep_prob=graph.get_tensor_by_name("fintune_whimh/Placeholder:0")

In [53]:
print keep_prob
print x_tfed
print predctions

Tensor("fintune_whimh/Placeholder:0", dtype=float32)
Tensor("feature_x:0", shape=(?, 7, 7, 512), dtype=float32)
Tensor("fintune_whimh/measure/predict/predictions_:0", shape=(?,), dtype=int64)


In [54]:
w=sess.run(soft_predctions, feed_dict={x_tfed:feature_x[:5],keep_prob:1.0})

In [55]:
print [i[1] for i in w]
print y_ID[:5]
#1 0 0 1 1

[0.99948871, 5.9986294e-05, 0.00074942858, 0.99644464, 0.98935246]
[    1    10   100  1000 10000]


In [56]:
#train_writer = tf.train.SummaryWriter('/tmp/loser1/train',sess.graph)

In [57]:
testing_prob=sess.run(soft_predctions, feed_dict={x_tfed:feature_x,keep_prob:1.0})

In [58]:
testing_prob= [i[1]  for i in testing_prob]

In [59]:
data=zip(testing_prob,y_ID)

In [60]:
import csv
f = open("/home/stream/whimh2.0/Bibi/vgg16_pool5_test.csv","w")
w = csv.writer(f)
w.writerows(data)
f.close()

In [61]:
tf.reset_default_graph()
sess.close()